{
  global:
    gng_init;
    gng_setParameter;
    gng_setPointCloud;
    gng_exec;
    gng_getTopologicalMap;
    gng_getDownSampling;
    gng_getAffineTransformedInputPointCloud;
    gng_setInferredClusterLabels;
  local:
    *;
};