topics:
  - alias: graph
    topic: /topological_map
    kind: topological_map
    role: graph
    required: true

  - alias: candidate_graph
    topic: /ToPoDualArm/cand_topological_map
    kind: topological_map
    role: candidate_graph
    compact: true
    sample_every: 1

  - alias: pointcloud
    topic: /topo_points
    kind: pointcloud2
    role: pointcloud
    sample_every: 1

  - alias: metrics
    topic: /grasp_candidate_metrics
    kind: generic
    role: metrics

  - alias: evaluation_metrics
    topic: /evaluation_metrics
    kind: generic
    role: evaluation_metrics

  - alias: left_grip_V_graph
    topic: /ToPoDualArm/L_grip_V_topological_map
    kind: topological_map
    role: gripper_volume_graph
    required: false

  - alias: right_grip_V_graph
    topic: /ToPoDualArm/R_grip_V_topological_map
    kind: topological_map
    role: gripper_volume_graph
    required: false

  - alias: left_grip_minV_graph
    topic: /ToPoDualArm/L_grip_minV_topological_map
    kind: topological_map
    role: gripper_volume_graph
    required: false

  - alias: right_grip_minV_graph
    topic: /ToPoDualArm/R_grip_minV_topological_map
    kind: topological_map
    role: gripper_volume_graph
    required: false
