topics:
  - alias: graph
    topic: /topological_map
    kind: topological_map
    role: graph
    required: true

  - alias: pointcloud
    topic: /camera/camera/depth/color/points
    kind: pointcloud2
    role: pointcloud
    sample_every: 1

  - alias: segmented
    topic: /scan/segmented
    kind: pointcloud2
    role: pointcloud
    sample_every: 1
