/**:
  ros__parameters:
    input_topic: /dynamixel/state/present
    output_topic: joint_states

    joint_ids:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7

      - 8
      - 8

      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17

      - 18
      - 18

    joint_names:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
      - right_gripper_left_joint
      - right_gripper_right_joint

      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - left_gripper_left_joint
      - left_gripper_right_joint


    joint_scales:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - -0.015
      - -0.015
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - -0.015
      - -0.015
