robot_viewer_bridge_node:
  ros__parameters:
    robot_name: "topoarm"
    robot_description_file: "package://gng_vlut_system/urdf/topoarm_description/urdf/topoarm_dual.urdf.xacro"
    arm_leaf_link_names: "left_link7,right_link7"
    joint_state_topic: "/joint_states"
    stream_topic: "/viewer/internal/stream/robot"
    frame_id: "world"
    publish_hz: 30.0
