offline_urdf_trainer:
  ros__parameters:
    gng_params:
      lambda: 50
      max_node_num: 10000
      num_samples: 1000000
      max_iterations: 1000000
      refine_iterations: 100000
      coord_edge_iterations: 200000
      learn_rate_s1: 0.08
      learn_rate_s2: 0.008
      max_edge_age: 500
      alpha: 0.5
      beta: 0.0005
      n_best_candidates: 4
      ais_threshold: 1.0
      start_node_num: 2