robot_bridge_node:
  ros__parameters:
    robot_ip: "192.168.4.40"
    robot_port: 8888
    listen_port: 8886
    update_hz: 50.0
    joint_state_topic: "/joint_states_real"
    joint_command_topic: "/joint_commands"
    joint_names: [
      "slave_j1", "slave_j2", "slave_j3", "slave_j4", "slave_j5", "slave_j6", "slave_gripper",
      "master_j1", "master_j2", "master_j3", "master_j4", "master_j5", "master_j6", "master_gripper"
    ]
