/**:
  ros__parameters:
    input_topics: "/topo_voxel_ids"  #複数トピックはカンマ区切りで指定
    output_voxel_topic: "voxel_merged"
    occupied_voxels_topic: "occupied_voxels"
    danger_voxels_topic: "danger_voxels"
    target_frame_id: "ToPoDualArm/base_link"
    target_voxel_size: 0.02
    target_x_shift: 42
    target_y_shift: 21
    target_z_shift: 0
    target_offset: 1000000
    danger_inflation: 0.05
    publish_hz: 10.0