ais_gng:
  ros__parameters:
    node.num_max: 20000
    node.learning_num: 4000
    node.unknown_learning_rate: 0.8
    node.eta_s1: 0.08
    node.eta_s2: 0.008
    node.edge_age_max: 100
    node.s1_reset_range: 0.1
    node.s1_age: [6, 6, 6, 3] #[default, safe, wall, unknown]
    node.clusted_s1_age: [20, 20, 6, 3] #[default, safe, wall, unknown]
    node.interval: [0.1, 0.4, 0.4, 0.05] #[default, safe, wall, unknown]
    node.static.age_min: 250 # 長期記憶の年齢

    ds.transformed: true
    ds.range_max: 0.2
    ds.all.num_max: 4000
    ds.unknown.num_max: 2000
    ds.human.num_max: 3000

    label.fuzzy.unknown: 0.6
    label.fuzzy.min: 0.5
    label.fuzzy.lpf_time_constant: 0.5

    cluster.num_min: 10
    cluster.velocity.lpf_time_constant: 0.5
    cluster.plane.volume: 10.0
    cluster.unknown.edge_distance_max: 0.2
    cluster.other.edge_distance_max: 0.4
    cluster.human.radius: 0.6
    cluster.human.hysteresis_age: 5
    cluster.human.confirmation_age: 5
    cluster.car.hysteresis_age: 5
    cluster.car.confirmation_age: 5
    cluster.safe_terrain.merge_distance_max: 0.25
    cluster.safe_terrain.merge_normal_angle_deg: 10.0
    cluster.non_safe.merge_distance_max: 0.0

    classify.human: true
    classify.human.model: "NN_human.pt"
    classify.car: false
    classify.car.model: "NN_car.pt"
    classify.threshold: 0.7
    classify.simple_reliability.human: 0.55
    classify.simple_reliability.car: 0.45
    classify.simple_reliability.unknown: 0.20

    input.point_cloud_num: 20000
    input.base_frame_id: "map"
    input.voxel_grid_unit: 0.1
    input.visualize: true
    input.local_coordinates: false
    input.x_min: -100.
    input.x_max: 100.
    input.y_min: -100.
    input.y_max: 100.
    input.z_min: -1.
    input.z_max: 20.
