FROM node:20-bookworm-slim

WORKDIR /ros2_ws/src/ToPoFuzzy-Viewer/frontend

COPY ToPoFuzzy-Viewer/frontend/package*.json ./
RUN npm ci

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
