FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

# ToPoArm実機ドライバのビルド依存関係
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-colcon-common-extensions \
    ros-humble-hardware-interface \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws

CMD ["/bin/bash"]
