# ROS 2 Fast DDSの大容量PointCloud2配送用UDPバッファ
net.core.rmem_default = 16777216
net.core.rmem_max = 67108864
net.core.wmem_default = 16777216
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 5000
