ais_gng_node:
  ros__parameters:
    node.num_max: 65534 # 65534
    node.learning_num: 5
    node.eta_s1: 0.4
    node.edge_age_max: 10
    node.s1_age_max: [10]
    node.interval: [0.05]

    cluster.num_min: 10
    cluster.velocity.lpf_time_constant: 0.5
    cluster.edge_distance_max: 0.1
    cluster.human.hysteresis_age: 10

    input.topic_names: ["/left_camera/depth/points", "/rear_camera/depth/points", "/right_camera/depth/points", "/front_camera/depth/points"]
    input.point_cloud_num: 1000000
    input.base_frame_id: "map"
    input.voxel_grid_unit: 0.05
    input.visualize: true
    input.x_min: -2.0
    input.x_max: 2.0
    input.y_min: -2.0
    input.y_max: 2.0
    input.z_min: 0.1
    input.z_max: 1.8