# /ns/dyn_handler:
/**:
    ros__parameters:
    # 開発用
        debug: false # true: デバイスとの接続に失敗してもエラーを出力しない/ false: エラーを出力して終了する
        no_use_command_line: false # true: プログラム用のトピックのみ使用する/ false: コマンドライン用のトピックも出力する
        # dummy_servo_id_list: [] # ダミーのサーボを作成する,同じIDのサーボが存在する場合でもダミーが優先される． 
    # 通信機器の設定
        device_name: /dev/ttyUSB0 # 通信するデバイス名
        # device_name: /dev/ttyACM0 # 通信するデバイス名(use OpenCR)
        baudrate: 1000000 # 通信速度
        latency_timer: 1  # 通信のインターバル
    # 通信の設定
        dyn_comm/retry_num: 5
        dyn_comm/inerval_msec: 4
        dyn_comm/verbose: false
    # サーボの設定
        init/baudrate_auto_set: false # 探索前に，全てのサーボと全てのBaudrateに対して，baudrateの書き込みをするかどうか
        init/expected_servo_num: 0
        init/servo_auto_search:
            min_id: 0
            max_id: 4
            retry_times: 3
        init/hardware_error_auto_clean: true # 初期化時に Hardware error を自動でクリアするかどうか
        init/torque_auto_enable: true # 初期化時に Torque を自動でONにするかどうか
        term/torque_auto_disable: true # 終了時に Torque を自動でOFFにするかどうか
        term/servo_auto_stop: true # 終了時に電流・速度制御のサーボを停止するかどうか
    # デフォルト値の設定
        default/profile_acc: 600.0 # deg/s^2
        default/profile_vel: 100.0 # deg/s
        default/return_delay_time: 0.0 # us [double]
    # ループの設定
        loop_rate: 100 # メインループの周期
        verbose_ratio: 300 # メインループのlog出力の割合(処理時間，通信の成功率), ex 100なら100回に1回出力
        pub_outdated_present_value: true # 最新でないpresent_XXXをpublishするかどうか. false ならば 直近のループでreadした Present の要素のみmsgに含められる．
        pub_ratio/present: # present_XXXを読み取る割合
            pwm:                  0 # この回数に一回present_pwmを読み取る
            current:              0 # この回数に一回present_currentを読み取る
            velocity:             1 # この回数に一回present_velocityを読み取る
            position:             1 # この回数に一回present_positionを読み取る
            velocity_trajectory:  0 # この回数に一回velocity_trajectoryを読み取る
            position_trajectory:  0 # この回数に一回position_trajectoryを読み取る
            input_voltage:        0 # この回数に一回present_input_voltageを読み取る
            temperature:         0 # この回数に一回present_temperatureを読み取る
        pub_ratio/status: 1 # この回数に一回 Status を読み取る, 0=初回のみ
        pub_ratio/goal: 0  # この回数に一回 Goal を読み取る, 0=初回のみ
        pub_ratio/gain: 0 # この回数に一回 Gain を読み取る, 0=初回のみ
        pub_ratio/limit: 0 # この回数に一回 Limit を読み取る, 0=初回のみ
        pub_ratio/error: 0 # この回数に一回 Hardware error を読み取る, 0=初回のみ
    # Read/Write方式
        method/fast_read: false
        method/split_read: false
        method/split_write: true
    # デバッグ用
        max_log_width: 6
        verbose/callback: false
        verbose/write_status: false
        verbose/write_goal: false
        verbose/write_gain: false
        verbose/write_limit: false
        verbose/read_status/raw: false
        verbose/read_status/err: false
        verbose/read_present/raw: false
        verbose/read_present/err: false
        verbose/read_goal/raw: false
        verbose/read_goal/err: false
        verbose/read_gain/raw: false
        verbose/read_gain/err: false
        verbose/read_limit/raw: false
        verbose/read_limit/err: false
        verbose/read_hardware_error: false
    # Optonal機能
        option/external_port:
            use : false # External Portの機能を使うかどうか
            pub_ratio/data : 10  # この回数に一回 Data を読み取る.
            pub_ratio/mode : 100 # この回数に一回 Mode を読み取る, ROM値なので大きくても問題ない．
            verbose/callback : false
            verbose/write    : false
            verbose/read/raw : false
            verbose/read/err : false