import * as THREE from 'three';
export async function runEnvironmentQA(env){const saved=env.getState(),tests=[],assert=(x,m)=>{if(!x)throw Error(m);},test=async(name,fn)=>{try{tests.push({name,passed:true,details:await fn()});}catch(e){tests.push({name,passed:false,error:e.message});}};
 try{
 await test('World/table reparent preserves pose',()=>{const item=env.items[0],g=item.group;env.scene.updateMatrixWorld(true);const before=g.matrixWorld.clone();env.scene.attach(g);env.scene.updateMatrixWorld(true);assert(before.elements.every((v,i)=>Math.abs(v-g.matrixWorld.elements[i])<1e-9),'World transform changed');env.objectRoot.attach(g);return '4x4 transform preserved';});
 await test('XYZ, full RPY, nonuniform scales round trip',async()=>{const v=structuredClone(saved);v.objects[0]={...v.objects[0],parent:'world',position:[1.2,-.4,.23],rpy:[.12,-.23,.34],scaleXYZ:[2,.7,1.5]};v.table={...v.table,roll:.12,pitch:-.05,yaw:.24,height:.48};await env.load(v);const a=env.getState();assert(JSON.stringify(v.objects)===JSON.stringify(a.objects)&&Object.keys(v.table).every(k=>v.table[k]===a.table[k])&&JSON.stringify(v.mid360)===JSON.stringify(a.mid360),'Saved scene differs after loading');return a.objects[0];});
 await test('Invalid scene leaves existing scene unchanged',async()=>{const before=JSON.stringify(env.getState()),v=env.getState();v.objects[0].scaleXYZ=[1,-1,1];let rejected=false;try{await env.load(v);}catch{rejected=true;}assert(rejected&&JSON.stringify(env.getState())===before,'Invalid scene mutated state');return 'Rejected before mutation';});
 await test('Legacy v1 scene remains loadable',async()=>{await env.load({format:'topo-workspace/1',table:{type:'wood',x:.5,y:0,z:.12,yaw:.2,width:.6,depth:.8},objects:[{type:'box',color:'#aabbcc',position:[.1,-.1,.02],yaw:.3,scale:1.2}]});const v=env.getState();assert(v.format==='topo-workspace/2'&&v.objects[0].rpy[2]===.3&&v.objects[0].scaleXYZ[1]===1.2,'Legacy migration incorrect');return v.objects[0];});
 await test('Both vehicle meshes have physical dimensions and details',async()=>{const details=[];for(const type of ['ferrari','concept']){const x=await env.addVehicle(type),s=x.group.userData.nativeSize;assert(s[0]>3&&s[0]<7&&s[1]>1.3&&s[1]<3&&s[2]>.8&&s[2]<2.5,'Vehicle axes/units incorrect: '+s);x.group.updateMatrixWorld(true);const front=x.group.getObjectByName(type==='ferrari'?'lights':'BodyHeadlights'),rear=x.group.getObjectByName(type==='ferrari'?'lights_red':'BodyTaillights');if(front&&rear){const a=new THREE.Box3().setFromObject(front,true).getCenter(new THREE.Vector3()),b=new THREE.Box3().setFromObject(rear,true).getCenter(new THREE.Vector3());assert(a.x>b.x,'Vehicle front is not +X');}let triangles=0;x.group.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;});assert(triangles>10000,'Vehicle detail missing');details.push({type,size:s,triangles});}return details;});
 }finally{await env.load(saved);}
 return{timestamp:new Date().toISOString(),passed:tests.every(x=>x.passed),tests};}
