import {loadMeasuredScan,measuredMetadata} from './measured-scan.js';
import * as THREE from './vendor/three/build/three.module.js';
import {buildGeometry,prepareMeshes,firstSurface,scanDirection,scan,defaultLidarConfig,validateLidarConfig,lidarPLY,packedPositions,waistLidarMount,PETAL_SCAN} from './lidar-core.js';
export async function runLidarQA(){await loadMeasuredScan();const tests=[],assert=(x,m)=>{if(!x)throw Error(m);},test=(name,fn)=>{try{tests.push({name,passed:true,details:fn()});}catch(e){tests.push({name,passed:false,error:e.message});}};
 const map=new Map(),geoms=[];const descriptor=(id,g,matrix)=>{const b=buildGeometry({position:g.attributes.position.array,index:g.index?.array});map.set(id,b);geoms.push(g,b);return{id,geometry:id,matrix:matrix.toArray(),reflectance:.5};};const origin=new THREE.Vector3(),ray=new THREE.Vector3(1,0,0),identity=new THREE.Matrix4();
 test('Legacy nominal FOV 360° / −7°..52°',()=>{let lo=90,hi=-90;const bins=new Set();for(let i=0;i<20000;i++){const d=scanDirection(i),e=Math.asin(d.z)*180/Math.PI;lo=Math.min(lo,e);hi=Math.max(hi,e);assert(Math.abs(d.length()-1)<1e-12,'Ray is not normalized');bins.add(Math.min(35,Math.floor((Math.atan2(d.y,d.x)+Math.PI)*180/Math.PI/10)));}assert(lo>=-7.000001&&hi<=52.000001&&hi>51.9&&bins.size>=36,'FOV incorrect');return{minDeg:lo,maxDeg:hi,bins:bins.size};});
 test('Legacy petal path is continuous and does not repeat each revolution',()=>{let maxStep=0,turns=0,lastDiff=0;let prev=scanDirection(0),prevE=Math.asin(prev.z);for(let i=1;i<20000;i++){const d=scanDirection(i),e=Math.asin(d.z),diff=e-prevE;maxStep=Math.max(maxStep,prev.angleTo(d));if(diff*lastDiff<0)turns++;prev=d;prevE=e;lastDiff=diff;}const shift=scanDirection(0).angleTo(scanDirection(20000));assert(maxStep<.005&&turns>=12&&shift>.05,'Discontinuous or repeating pattern');return{maxAdjacentAngleDeg:maxStep*180/Math.PI,elevationTurns:turns,oneRevolutionShiftDeg:shift*180/Math.PI};});
 test('Legacy longer integration fills additional angular cells',()=>{const bins=new Set(),counts=[];for(let i=0;i<200000;i++){const d=scanDirection(i),a=(Math.atan2(d.y,d.x)+Math.PI)*180/Math.PI,e=Math.asin(d.z)*180/Math.PI;bins.add(Math.floor(a/2)+','+Math.floor((e+7)/2));if([4999,19999,99999,199999].includes(i))counts.push(bins.size);}assert(counts.every((v,i)=>!i||v>counts[i-1])&&counts[3]>counts[1]*1.3,'Coverage does not grow');return{windowsSeconds:[.025,.1,.5,1],angularCells2deg:counts};});
 test('標準モデルの45°取付・腰Yaw追従',()=>{const c=waistLidarMount(),m=new THREE.Matrix4().compose(new THREE.Vector3(...c.position),new THREE.Quaternion().setFromEuler(new THREE.Euler(...c.rpy,'ZYX')),new THREE.Vector3(1,1,1)),forward=new THREE.Vector3(Math.cos(22.5*Math.PI/180),0,Math.sin(22.5*Math.PI/180)).transformDirection(m);assert(c.parent==='torso_link'&&Math.abs(c.rpy[1]-Math.PI/4)<1e-10&&Math.abs(Math.asin(forward.z)*180/Math.PI+22.5)<1e-10,'正面方向の傾斜不一致');const yaw=new THREE.Matrix4().makeRotationZ(Math.PI/2),p=new THREE.Vector3().setFromMatrixPosition(yaw.multiply(m));assert(Math.abs(p.y-.07769)<1e-10&&Math.abs(p.z-.105)<1e-10,'腰Yaw追従の不一致');return{forward_center_deg:-22.5,front_vertical_fov_deg:[-52,7]};});
 test('Interleaved CAD positions retain geometry without normals as vertices',()=>{const a=new THREE.InterleavedBufferAttribute(new THREE.InterleavedBuffer(new Float32Array([1,2,3,0,0,1,4,5,6,0,1,0]),6),3,0);assert(JSON.stringify(Array.from(packedPositions(a)))==='[1,2,3,4,5,6]','Interleaved packing incorrect');return{vertices:a.count};});
 const far=descriptor(1,new THREE.BoxGeometry(.2,4,4),new THREE.Matrix4().makeTranslation(2.1,0,0));
 test('2 m plane is measured at the actual triangle',()=>{const h=firstSurface(origin,ray,prepareMeshes([far],map));assert(Math.abs(h.distance-2)<1e-7,'Plane range incorrect');return{errorMm:Math.abs(h.distance-2)*1000};});
 test('Nearest surface occludes the background',()=>{const near=descriptor(2,new THREE.BoxGeometry(.2,1,1),new THREE.Matrix4().makeTranslation(1,0,0));const h=firstSurface(origin,ray,prepareMeshes([far,near],map));assert(h.id===2&&Math.abs(h.distance-.9)<1e-7,'Occlusion incorrect');return h.distance;});
 test('Below-minimum occluder blocks rays',()=>{const near=descriptor(3,new THREE.BoxGeometry(.04,3,3),new THREE.Matrix4().makeTranslation(.06,0,0));const c={...defaultLidarConfig(),scanPattern:'petal',beams:100};const f=scan(c,identity.toArray(),prepareMeshes([far,near],map));assert(f.nearRejected>10,'Near surfaces are being skipped');return{nearRejected:f.nearRejected};});
 test('Nonuniform size and arbitrary pose use transformed geometry',()=>{const m=new THREE.Matrix4().compose(new THREE.Vector3(3,.4,.2),new THREE.Quaternion().setFromEuler(new THREE.Euler(.13,-.21,.4,'ZYX')),new THREE.Vector3(2,.7,1.2)),d=descriptor(4,new THREE.BoxGeometry(1,1,1),m),start=new THREE.Vector3(-2,0,0).applyMatrix4(m),toward=new THREE.Vector3(1,0,0).transformDirection(m),h=firstSurface(start,toward,prepareMeshes([d],map));assert(Math.abs(h.distance-3)<1e-6,'Scaled range not in metres');return{errorMm:Math.abs(h.distance-3)*1000};});
 const room=descriptor(5,new THREE.BoxGeometry(20,20,20),identity);let frame;
 test('20,000 rays versus analytic box surfaces',()=>{const c={...defaultLidarConfig(),scanPattern:'petal'};frame=scan(c,identity.toArray(),prepareMeshes([room],map));assert(frame.count===20000,'Beam loss');let max=0;for(let i=0;i<frame.count;i++){const d=scanDirection(i),r=10/Math.max(Math.abs(d.x),Math.abs(d.y),Math.abs(d.z));max=Math.max(max,Math.abs(r-frame.range[i]));}assert(max<2e-6,'Box error exceeds 0.002 mm');return{points:frame.count,maxErrorMm:max*1000,ms:frame.ms};});
 test('Noise mode is seeded and distinct from geometric truth',()=>{const c={...defaultLidarConfig(),scanPattern:'petal',mode:'noise',beams:1000},a=scan(c,identity.toArray(),prepareMeshes([room],map)),b=scan(c,identity.toArray(),prepareMeshes([room],map));assert(a.range.every((v,i)=>v===b.range[i]),'Non-reproducible noise');assert(Math.abs(a.range[0]-frame.range[0])>.00001,'No noise');return{sigmaM:c.noiseSigma};});
 test('Splitting frames preserves petal timing and point geometry',()=>{const meshes=prepareMeshes([room],map),c={...defaultLidarConfig(),scanPattern:'petal',beams:4000,duration:.02},all=scan(c,identity.toArray(),meshes,60000,.3),half={...c,beams:2000,duration:.01},a=scan(half,identity.toArray(),meshes,60000,.3),b=scan(half,identity.toArray(),meshes,62000,.31);assert(all.count===a.count+b.count,'Split count');let max=0;for(let i=0;i<all.xyz.length;i++)max=Math.max(max,Math.abs(all.xyz[i]-(i<a.xyz.length?a.xyz[i]:b.xyz[i-a.xyz.length])));assert(max<1e-5,'Frame boundary resets phase');return{maxPositionErrorMm:max*1000};});
 test('Legacy scan remains available and old configurations still load',()=>{const c=validateLidarConfig({parent:'neck_tilt_link'}),d=scanDirection(123,new THREE.Vector3(),'low-discrepancy');assert(c.scanPattern==='measured'&&d.distanceTo(scanDirection(123,new THREE.Vector3(),'low-discrepancy',42))===0,'Legacy mode compatibility');return PETAL_SCAN.model;});
 test('PLY holds every point, timestamp, object and beam',()=>{const f={...frame,pose:new THREE.Matrix4().makeTranslation(1,2,3).toArray()},b=lidarPLY(f,true),text=new TextDecoder().decode(new Uint8Array(b,0,600)),header=text.indexOf('end_header\n')+11,d=new DataView(b);assert(b.byteLength===header+f.count*29,'PLY size');assert(Math.abs(d.getFloat32(header,true)-(f.xyz[0]+1))<1e-6,'World transform');assert(d.getUint32(header+24,true)===5,'Object ID');return{points:f.count,bytes:b.byteLength};});

 test('Official measured slots keep missing directions and point order',()=>{const c=defaultLidarConfig(),f=scan(c,identity.toArray(),prepareMeshes([room],map));let known=0,max=0;for(let i=0;i<c.beams;i++){const d=scanDirection(i,new THREE.Vector3(),'measured');if(d.lengthSq()===0){assert(f.slotStatus[i]===1,'Unknown slot invented');continue;}const r=10/Math.max(Math.abs(d.x),Math.abs(d.y),Math.abs(d.z));assert(f.beamIndex[known]===i,'Sequence changed');max=Math.max(max,Math.abs(r-f.range[known]));known++;}assert(known===f.count&&f.count+f.unknownDirections===c.beams&&f.unknownDirections>0&&max<2e-6,'Measured count or range');return{slots:c.beams,known,unknown:f.unknownDirections,maxErrorMm:max*1000};});
 test('Measured sample wraps exactly after 5 seconds and splits without resets',()=>{const n=measuredMetadata().slots;for(const i of [380,10001,582333])assert(scanDirection(i,new THREE.Vector3(),'measured').distanceTo(scanDirection(i+n,new THREE.Vector3(),'measured'))===0,'Loop mismatch');const meshes=prepareMeshes([room],map),c={...defaultLidarConfig(),duration:.02,beams:4000},a=scan(c,identity.toArray(),meshes,9800),half={...c,duration:.01,beams:2000},b=scan(half,identity.toArray(),meshes,9800),d=scan(half,identity.toArray(),meshes,11800);const joined=new Float32Array([...b.xyz,...d.xyz]);assert(a.xyz.every((v,i)=>v===joined[i]),'Frame boundary changes measured rays');return{slots:n,seconds:5};});
 test('Every slot is accounted for with no phantom points',()=>{const f=scan(defaultLidarConfig(),identity.toArray(),[]);assert(f.count===0&&f.noReturn+f.unknownDirections===20000&&f.slotRange.every(v=>v===0),'Empty scene has returns');return{emptySceneNoHit:f.noReturn,unknown:f.unknownDirections};});
 test('Invalid configuration is rejected',()=>{let n=0;for(const v of [{maxRange:0},{beams:1},{position:[NaN,0,0]},{parent:'missing'},{noiseSigma:-1},{scanPattern:'missing'}])try{validateLidarConfig(v);}catch{n++;}assert(n===6,'Invalid config accepted');return n;});
 for(const g of geoms)g.dispose();return{timestamp:new Date().toISOString(),passed:tests.every(x=>x.passed),tests};
}
