import {CloudColorControls,displayPLY} from './pointcloud-colors.js';
import {loadMeasuredScan,measuredMetadata} from './measured-scan.js';
import * as THREE from 'three';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {defaultLidarConfig,validateLidarConfig,lidarPLY,waistLidarMount,scanDirection,PETAL_SCAN,packedPositions} from './lidar-core.js';
import {robot_snapshot} from './robot-ros-state.js';
import {zipFiles} from './capture-zip.js';
const $=id=>document.getElementById(id),rad=Math.PI/180;
export class LidarWorkspace{
 constructor({scene,overlay,robot,renderer,camera,environment,toast,download,onLayers}){
  Object.assign(this,{scene,overlay,robot,renderer,camera,environment,toast,download,onLayers});this.config=defaultLidarConfig();this.sequence=0;this.scanTime=0;this.known=new Set();this.live=false;this.busy=false;this.lastTime=0;this.id=0;
  this.mount=new THREE.Group();this.mount.name='MID-360 sensor origin';this.model=new THREE.Group();this.mount.add(this.model);scene.add(this.mount);this.mount.visible=false;
  this.buildBracket();
  this.axes=new THREE.AxesHelper(.13);this.axes.visible=false;this.axes.layers.set(2);this.mount.add(this.axes);
  this.cloud=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({size:2,sizeAttenuation:false,vertexColors:true,toneMapped:false}));this.cloud.layers.set(2);this.cloud.frustumCulled=false;this.cloud.visible=false;scene.add(this.cloud);
  this.generation=0;this.createWorker();
  this.ui();this.apply();loadMeasuredScan().then(()=>{this.drawPattern();this.publish();}).catch(e=>this.toast(e.message));environment.getSensorState=()=>({...structuredClone(this.config)});environment.validateSensorState=validateLidarConfig;environment.loadSensorState=c=>this.configure(c);this.publish();
 }
 ui(){
  $('lidar-panel').innerHTML=`<div class="panel-heading"><div><span class="eyebrow">360° LiDAR</span><h2>Livox MID-360</h2></div><span class="chip">200k slots/s</span></div>
  <label class="sensor-enable"><input type="checkbox" id="lidar-enable"> Mid-360を有効にする</label><p class="sub-note">公式CADから生成した実寸STL。水平360° / 垂直−7°〜52°。有効化して「1回取得」または連続取得を開始します。</p>
  <div class="row-actions"><button id="lidar-once" disabled>1回取得</button><button id="lidar-live" disabled>▶ 連続取得</button></div>
  <label class="field-label">走査パターン<select id="lidar-pattern"><option value="measured">実測 · Livox公式サンプルの走査方向</option><option value="petal">旧・花びらの数式近似</option><option value="low-discrepancy">均等分布 · 旧方式</option></select></label>
  <figure class="lidar-pattern-preview"><figcaption>走査方向 <span>センサー上面から · 距離ではありません</span></figcaption><canvas id="lidar-pattern-preview" width="320" height="210" role="img" aria-label="MID-360の花びら状走査軌跡"></canvas><div id="lidar-pattern-time" class="sub-note"></div></figure>
  <p class="sub-note">実測モードは5秒の公式記録を順番に再生します。方向不明の無効スロットは補間しません。実機個体・環境に依存する欠損まで一致するものではありません。</p><label class="field-label">取得モード<select id="lidar-mode"><option value="ideal">幾何真値 · 最近傍の表面</option><option value="noise">距離ノイズ近似 · Gaussian</option></select></label>
  <div class="field-grid"><label>積分時間<select id="lidar-duration"><option value="0.025">0.025 s · 5,000スロット</option><option value="0.1" selected>0.1 s · 20,000スロット</option><option value="0.5">0.5 s · 100,000スロット</option><option value="1">1 s · 200,000スロット</option></select></label><label>最大距離 m<input id="lidar-range" type="number" min="0.2" max="100" step="1" value="40"></label><label>ノイズ σ mm<input id="lidar-noise" type="number" min="0" max="100" value="20"></label><label>乱数シード<input id="lidar-seed" type="number" value="12345" step="1"></label></div>
  <div id="lidar-stats" class="sensor-stats" role="status">無効 · 取得待ち</div><div class="row-actions"><label><input id="lidar-show" type="checkbox" checked>点群を表示</label><label><input id="lidar-only" type="checkbox">点群のみ</label><label><input id="lidar-axes" type="checkbox">座標軸</label></div>
  <div id="lidar-colors" class="cloud-color-controls"></div><div class="row-actions"><select id="lidar-frame"><option value="world">base_footprint [m]</option><option value="sensor">mid360 [m]</option></select><button id="lidar-export" disabled>↓ 点群一式 ZIP</button></div>
  <details open><summary>取付位置・姿勢</summary><button id="lidar-waist-preset" class="wide-button">腰上・前方25°の配置に戻す</button><label class="field-label">親座標<select id="lidar-parent"><option value="torso_link">腰上リンク · 腰Yawに追従</option><option value="neck_tilt_link">首 Pitchリンク</option><option value="neck_pan_link">首 Yawリンク</option><option value="base_footprint">ロボット基準</option><option value="world">ワールド固定</option></select></label><div class="field-grid">${['x','y','z','roll','pitch','yaw'].map(k=>`<label>${k.toUpperCase()} ${k.length===1?'mm':'°'}<input id="lidar-${k}" type="number" step="${k.length===1?'5':'1'}" value="0"></label>`).join('')}</div><p class="sub-note">初期位置は腰Yaw軸から前77.69 mm・上105 mm（従来より50 mm上）、前下がり25°。柱と取付板の最小X隙間は約1 mm。正面方向の上下視野は約−32°〜+27°です。XYZは親リンク基準、軸はX前・Y左・Z上、RPYはRz·Ry·Rx。腰上リンクを選ぶと腰に追従します。</p></details>
  <details><summary>モデル・シミュレーションの範囲</summary><p class="sub-note">レイと三角形の最近交点をBVHで計算。視界を遮る物体、車体、ロボット、天板も計測します。0.1 m未満の遮蔽物の奥は透過しません。ガラスも幾何学的な表面として扱います。</p><p class="sub-note">実測モードは公式LVX2のXYZから方向を正規化して再走査します。元記録の欠損・mm量子化を含み、5秒でループします。旧花びらは数式近似です。反射率・多重反射・IMU・走査中の動きは再現しません。各フレームは開始時の姿勢とシーンを固定します。20万本/sはシミュレーション時間上の値で、実行速度は下に表示します。</p><a href="assets/mid360/mid-360.stl" download>公式CAD変換 STL（mm）</a> · <a href="ASSET_SOURCES.md" target="_blank">モデル出典</a></details>
  <button id="lidar-verify" class="wide-button">点群の幾何精度を検証</button><output id="lidar-qa"></output>`;
  this.colorControls=new CloudColorControls($('lidar-colors'),'lidar','reflectance',()=>{if(this.last)this.updateCloud(this.last);this.publish();});
  $('lidar-enable').onchange=async()=>{this.config.enabled=$('lidar-enable').checked;this.apply();if(this.config.enabled)try{await this.loadModel();this.toast('Mid-360を有効にしました');}catch(e){this.toast('STL読込エラー：'+e.message);}};
  $('lidar-once').onclick=()=>this.capture();$('lidar-live').onclick=()=>{this.live=!this.live;$('lidar-live').textContent=this.live?'■ 停止':'▶ 連続取得';if(this.live)this.capture();this.publish();};
  $('lidar-pattern').onchange=()=>{this.config.scanPattern=$('lidar-pattern').value;this.drawPattern();this.publish();};
  $('lidar-mode').onchange=()=>{this.config.mode=$('lidar-mode').value;};$('lidar-duration').onchange=()=>{this.config.duration=+$('lidar-duration').value;this.config.beams=Math.round(this.config.duration*200000);this.drawPattern();this.publish();};
  $('lidar-waist-preset').onclick=()=>{Object.assign(this.config,waistLidarMount());this.apply();this.toast('MID-360を腰上・前下がり25°に配置しました');};
  for(const [id,key,scale,min,max] of [['range','maxRange',1,.2,100],['noise','noiseSigma',.001,0,100],['seed','seed',1,0,4294967295]]){const el=$('lidar-'+id);el.oninput=()=>{if(Number.isFinite(el.valueAsNumber))this.config[key]=THREE.MathUtils.clamp(el.valueAsNumber,min,max)*scale;};}
  for(const [i,k]of['x','y','z','roll','pitch','yaw'].entries()){$('lidar-'+k).oninput=()=>{const v=$('lidar-'+k).valueAsNumber;if(!Number.isFinite(v))return;if(i<3)this.config.position[i]=THREE.MathUtils.clamp(v/1000,-100,100);else this.config.rpy[i-3]=v*rad;this.apply();};}
  $('lidar-parent').onchange=()=>{this.config.parent=$('lidar-parent').value;this.apply();};
  for(const id of ['lidar-show','lidar-only'])$(id).onchange=()=>this.setCloud();$('lidar-axes').onchange=()=>{this.axes.visible=$('lidar-axes').checked;this.onLayers();};$('lidar-export').onclick=()=>this.exportFrame();
  $('lidar-verify').onclick=async()=>{const b=$('lidar-verify');b.disabled=true;try{const {runLidarQA}=await import('./lidar-qa.js'),r=await runLidarQA();$('lidar-qa').textContent=`${r.passed?'PASS':'FAIL'} · ${r.tests.filter(x=>x.passed).length}/${r.tests.length}\n`+r.tests.map(x=>(x.passed?'✓ ':'✗ ')+x.name+(x.error?' '+x.error:'')).join('\n');document.documentElement.dataset.lidarQa=JSON.stringify(r);}catch(e){$('lidar-qa').textContent=e.message;}finally{b.disabled=false;}};
 }
 buildBracket(){
  const metal=new THREE.MeshStandardMaterial({color:'#424a4e',metalness:.75,roughness:.32}),silver=new THREE.MeshStandardMaterial({color:'#aab6bc',metalness:.85,roughness:.24});
  this.support=new THREE.Group();this.support.name='MID-360 waist mounting bracket';this.scene.add(this.support);
  const back=new THREE.Mesh(new THREE.BoxGeometry(.004,.068,.05),metal);this.supportBack=back;back.position.set(.0385,0,.080);back.castShadow=back.receiveShadow=true;this.support.add(back);
  this.supportBars=[-1,1].map(()=>{const mesh=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,12),metal);mesh.castShadow=mesh.receiveShadow=true;this.support.add(mesh);return mesh;});
  this.mountPlate=new THREE.Group();this.mountPlate.name='MID-360 tilted mounting plate';this.mount.add(this.mountPlate);
  const plate=new THREE.Mesh(new THREE.BoxGeometry(.064,.070,.003),metal);plate.position.z=-.028;plate.castShadow=plate.receiveShadow=true;this.mountPlate.add(plate);
  for(const x of [-.027,.027])for(const y of [-.027,.027]){const bolt=new THREE.Mesh(new THREE.CylinderGeometry(.0025,.0025,.002,6),silver);bolt.rotation.x=Math.PI/2;bolt.position.set(x,y,-.0255);this.mountPlate.add(bolt);}
 }
 updateBracket(parent){
  parent.add(this.support);this.support.visible=this.config.enabled&&this.config.parent==='torso_link';this.mountPlate.visible=this.config.parent==='torso_link';
  this.supportBack.position.z=this.config.position[2]-.025;const q=this.mount.quaternion,offset=this.mount.position,up=new THREE.Vector3(0,1,0);
  for(const [i,s]of[-1,1].entries()){const a=new THREE.Vector3(.0405,s*.026,this.config.position[2]-.025),b=new THREE.Vector3(0,s*.026,-.030).applyQuaternion(q).add(offset),d=b.clone().sub(a),bar=this.supportBars[i];bar.position.copy(a).add(b).multiplyScalar(.5);bar.quaternion.setFromUnitVectors(up,d.clone().normalize());bar.scale.set(.0035,Math.max(.001,d.length()),.0035);}
 }
 drawPattern(startTime=this.scanTime,duration=this.config.duration,beamStart=this.sequence,config=this.config){
  const canvas=$('lidar-pattern-preview');if(!canvas)return;if(config.scanPattern==='measured'&&!measuredMetadata()){$('lidar-pattern-time').textContent='公式走査データ読込中…';return;}const ctx=canvas.getContext('2d'),cx=160,cy=105,R=86;
  ctx.clearRect(0,0,320,210);ctx.fillStyle='#fbf9fc';ctx.fillRect(0,0,320,210);ctx.strokeStyle='#e8deeb';ctx.lineWidth=1;
  for(const r of [R*.392,R*.65,R]){ctx.beginPath();ctx.arc(cx,cy,r,0,2*Math.PI);ctx.stroke();}
  ctx.beginPath();ctx.moveTo(cx-R,cy);ctx.lineTo(cx+R,cy);ctx.moveTo(cx,cy-R);ctx.lineTo(cx,cy+R);ctx.stroke();ctx.fillStyle='#80658a';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText('X 前',cx,12);ctx.fillText('Y 左',44,cy+3);ctx.fillText('−7°',cx+R+17,cy+15);ctx.fillText('+52°',cx+R*.392+19,cy+15);
  const n=Math.min(20000,config.beams),d=new THREE.Vector3();let prev=null;
  for(let i=0;i<n;i++){const u=i/(n-1),beam=Math.floor(u*(config.beams-1)),t=startTime+beam*duration/config.beams;scanDirection(beamStart+beam,d,config.scanPattern,t);if(d.lengthSq()===0){prev=null;continue;}const e=Math.asin(d.z)/rad,a=Math.atan2(d.y,d.x),r=R*(90-e)/97,x=cx-r*Math.sin(a),y=cy-r*Math.cos(a);ctx.strokeStyle=ctx.fillStyle=`hsla(${285-165*u},65%,42%,.8)`;if(config.scanPattern==='petal'&&prev){ctx.beginPath();ctx.moveTo(...prev);ctx.lineTo(x,y);ctx.stroke();}else ctx.fillRect(x,y,1,1);prev=[x,y];}
  canvas.dataset.scanStart=String(startTime);canvas.dataset.pattern=config.scanPattern;
  $('lidar-pattern-time').textContent=`${startTime.toFixed(3)}〜${(startTime+duration).toFixed(3)} s · ${config.scanPattern==='measured'?'実測方向・元記録5秒でループ':config.scanPattern==='petal'?'旧数式近似':'均等分布の比較用'}`;
 }
 async loadModel(){if(this.modelReady)return;if(this.modelPromise)return this.modelPromise;this.modelPromise=(async()=>{const geometry=await new STLLoader().loadAsync('./assets/mid360/mid-360.stl');const pos=geometry.attributes.position,colors=new Float32Array(pos.count*3),silver=new THREE.Color('#858f95'),dark=new THREE.Color('#151c20'),base=new THREE.Color('#454d53');for(let i=0;i<pos.count;i++)(pos.getY(i)>6?dark:pos.getY(i)<-17?base:silver).toArray(colors,i*3);geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.scale(.001,.001,.001);geometry.rotateX(Math.PI/2);geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({vertexColors:true,metalness:.5,roughness:.28}));mesh.castShadow=mesh.receiveShadow=true;this.model.add(mesh);this.modelReady=true;this.renderer.shadowMap.needsUpdate=true;this.publish();})().catch(e=>{this.modelPromise=null;throw e;});return this.modelPromise;}

 configure(c){this.config=validateLidarConfig(c);this.live=false;this.apply();if(this.config.enabled)return this.loadModel();}
 apply(){const c=this.config,parent=c.parent==='world'?this.scene:this.robot.links[c.parent];if(!parent)throw Error('親リンクがありません：'+c.parent);parent.add(this.mount);this.mount.position.fromArray(c.position);this.mount.rotation.set(...c.rpy,'ZYX');this.mount.visible=c.enabled;this.updateBracket(parent);$('lidar-pattern').value=c.scanPattern;this.drawPattern();$('lidar-enable').checked=c.enabled;for(const id of ['lidar-once','lidar-live'])$(id).disabled=!c.enabled;
  if(!c.enabled){this.live=false;$('lidar-only').checked=false;this.cloud.visible=false;$('lidar-stats').textContent='無効 · 点群取得停止';}else $('lidar-stats').textContent=this.last?'設定変更済み · 次の取得で反映':'有効 · 取得待ち';$('lidar-live').textContent=this.live?'■ 停止':'▶ 連続取得';
  $('lidar-parent').value=c.parent;$('lidar-mode').value=c.mode;$('lidar-duration').value=String(c.duration);for(const [i,k]of['x','y','z','roll','pitch','yaw'].entries())if(document.activeElement!==$('lidar-'+k))$('lidar-'+k).value=(i<3?c.position[i]*1000:c.rpy[i-3]/rad).toFixed(2);$('lidar-range').value=c.maxRange;$('lidar-noise').value=c.noiseSigma*1000;$('lidar-seed').value=c.seed;this.renderer.shadowMap.needsUpdate=true;this.setCloud();this.publish();
 }
 setCloud(){this.cloud.visible=!!(this.config.enabled&&this.last&&($('lidar-show').checked||$('lidar-only').checked));this.cloudOnly=$('lidar-only').checked;this.onLayers();}
 tick(now){if(this.live&&!this.busy&&now-this.lastTime>=this.config.duration*1000)this.capture();}
 createWorker(){this.worker=new Worker(new URL('./lidar-worker.js',import.meta.url),{type:'module'});this.worker.onmessage=e=>this.receive(e.data);this.worker.onerror=e=>{this.finish_capture(null);this.busy=false;this.live=false;$('lidar-stats').textContent='取得エラー：'+e.message;this.publish({error:e.message});};}
 resetForRobot(robot){this.finish_capture(null);this.generation++;this.worker.terminate();this.createWorker();this.robot=robot;this.live=false;this.busy=false;this.pending=null;this.last=null;this.known.clear();this.sequence=0;this.scanTime=0;this.cloud.geometry.dispose();this.cloud.geometry=new THREE.BufferGeometry();this.cloud.visible=false;$('lidar-export').disabled=true;this.apply();}
 finish_capture(frame){this.resolve_capture?.(frame);this.resolve_capture=null;}
 async capture(){if(!this.config.enabled||this.busy)return null;const generation=this.generation;this.busy=true;this.lastTime=performance.now();$('lidar-stats').textContent='取得中 · シーンの表面を計測しています';
  try{await this.loadModel();if(this.config.scanPattern==='measured')await loadMeasuredScan();if(generation!==this.generation)return;this.scene.updateMatrixWorld(true);const geometries=[],meshes=[],names={},used=new Set(),exclude=new Set();this.mount.traverse(x=>exclude.add(x));let mid=1;
   this.scene.traverseVisible(o=>{if(!o.isMesh||exclude.has(o)||!o.layers.isEnabled(0)||!o.geometry.attributes.position)return;const g=o.geometry,key=g.uuid;used.add(key);if(!this.known.has(key)){geometries.push({id:key,position:packedPositions(g.attributes.position),index:g.index?Uint32Array.from(g.index.array):null});this.known.add(key);}const m=Array.isArray(o.material)?o.material[0]:o.material,color=m.color;const reflectance=color?THREE.MathUtils.clamp(.2126*color.r+.7152*color.g+.0722*color.b,0,1):.5;names[mid]=o.name||o.parent?.name||'surface';meshes.push({id:mid++,geometry:key,matrix:o.matrixWorld.toArray(),reflectance});});
   this.known=used;const config=structuredClone(this.config),id=++this.id,pose=this.mount.matrixWorld.toArray();this.pending={id,pose,config,beamStart:this.sequence,scanStart:this.scanTime,timestamp:new Date().toISOString(),workspace:this.environment.getState(),robotPose:this.robot.getPose(),robotModel:this.robot.modelId,robot_state:robot_snapshot(this.robot),names};this.sequence+=config.beams;this.scanTime+=config.duration;
   const completed=new Promise(resolve=>{this.resolve_capture=resolve;});
   this.publish();this.worker.postMessage({id,config,pose,meshes,geometries,start:this.pending.beamStart,startTime:this.pending.scanStart},geometries.flatMap(g=>[g.position.buffer,...(g.index?[g.index.buffer]:[])]));
   return await completed;
  }catch(e){if(generation!==this.generation)return null;this.finish_capture(null);this.busy=false;this.live=false;$('lidar-stats').textContent='取得エラー：'+e.message;this.publish({error:e.message});}
 }
 receive(d){if(d.id!==this.pending?.id)return;this.busy=false;if(d.error){this.finish_capture(null);this.live=false;this.known.clear();$('lidar-stats').textContent='取得エラー：'+d.error;this.publish({error:d.error});return;}const f={...this.pending,...d.frame};f.elapsedMs=performance.now()-this.lastTime;this.last=f;this.finish_capture(f);this.drawPattern(f.scanStart,f.config.duration,f.beamStart,f.config);this.updateCloud(f);this.setCloud();
  $('lidar-export').disabled=false;$('lidar-stats').textContent=`有効 ${f.count.toLocaleString()} 点 / ${f.config.beams.toLocaleString()} スロット\n参照方向なし ${f.unknownDirections.toLocaleString()} · 命中なし ${f.noReturn.toLocaleString()} · 近距離除外 ${f.nearRejected.toLocaleString()}\n計算 ${f.ms.toFixed(1)} ms · 全体 ${f.elapsedMs.toFixed(0)} ms\nシミュレーション ${f.config.duration} s · 実測最大 ${(1000/f.elapsedMs).toFixed(1)} frame/s`;this.publish();
 }
 updateCloud(f){const view=this.colorControls.compute(f.xyz,f.pose,f.reflectance);this.cloud.geometry.dispose();this.cloud.geometry=new THREE.BufferGeometry();this.cloud.geometry.setAttribute('position',new THREE.BufferAttribute(f.xyz,3));this.cloud.geometry.setAttribute('color',new THREE.BufferAttribute(view.colors,3));this.cloud.matrixAutoUpdate=false;this.cloud.matrix.fromArray(f.pose);this.cloud.updateMatrixWorld(true);}
 publish(extra={}){this.mount.updateWorldMatrix(true,false);document.documentElement.dataset.lidarState=JSON.stringify({model:this.robot.modelId,mountPose:this.mount.matrixWorld.toArray(),scanTime:this.scanTime,enabled:this.config.enabled,modelReady:!!this.modelReady,busy:this.busy,live:this.live,config:this.config,colors:this.colorControls?.summary,reference:measuredMetadata(),frame:this.last?{model:this.last.robotModel,id:this.last.id,count:this.last.count,beams:this.last.config.beams,ms:this.last.ms,elapsedMs:this.last.elapsedMs,pose:this.last.pose,nearRejected:this.last.nearRejected,unknownDirections:this.last.unknownDirections,noReturn:this.last.noReturn,rangeRejected:this.last.rangeRejected,scanStart:this.last.scanStart,beamStart:this.last.beamStart,pattern:this.last.config.scanPattern}:null,...extra});}
 async exportFrame(){const f=this.last;if(!f)return;const world=$('lidar-frame').value==='world',view=this.colorControls.compute(f.xyz,f.pose,f.reflectance);const meta={format:'topo-mid360/3',robot_model:f.robotModel,display_color:view.summary,unknown_directions:f.unknownDirections,no_return:f.noReturn,range_rejected:f.rangeRejected,slot_status_codes:{valid:0,reference_direction_unknown:1,no_surface_in_range:2,below_minimum_range:3,noise_out_of_range:4},id:f.id,timestamp:f.timestamp,point_frame:world?'base_footprint':'mid360',units:'m',pose_column_major:f.pose,config:f.config,beam_start:f.beamStart,scan_start_s:f.scanStart,valid_points:f.count,near_rejected:f.nearRejected,compute_ms:f.ms,elapsed_ms:f.elapsedMs,scan_pattern:f.config.scanPattern==='measured'?measuredMetadata():f.config.scanPattern==='petal'?{...PETAL_SCAN,description:'continuous non-repetitive flower imitation; not the proprietary Livox trajectory or calibrated point density'}:{model:'low-discrepancy-legacy'},pose_model:'all rays use one frozen scene and pose',reflectance:'synthetic linear visible albedo; not calibrated infrared intensity',objects:f.names,robot_joints_rad:f.robotPose};const bundle=await zipFiles({'frame.json':JSON.stringify(meta,null,2),'scene.json':JSON.stringify(f.workspace,null,2),'points.ply':lidarPLY(f,world),'points_display.ply':displayPLY(f.xyz,f.pose,view.rgb,world),'slot_status.u8':f.slotStatus,'slot_range.f32':f.slotRange,'xyz_sensor.f32':f.xyz,'range.f32':f.range,'time_offset.f32':f.time,'beam_index.u32':f.beamIndex,'object_id.u32':f.objectId});await this.download('MID360-capture.zip',bundle,'application/zip');}
}
