import * as THREE from 'three';
import {RGBDSensor,nominalCalibration,calibratedCamera,deproject,project,validateCalibration,binaryPLY} from './rgbd-core.js';
export async function runSensorQA(renderer){
 const results=[];let maxError=0;const check=(ok,msg)=>{if(!ok)throw Error(msg);},test=(name,fn)=>{try{results.push({name,passed:true,details:fn()});}catch(e){results.push({name,passed:false,error:e.message});}};
 const scene=new THREE.Scene(),mat=new THREE.MeshBasicMaterial({color:'#dc5020',side:THREE.DoubleSide}),plane=new THREE.Mesh(new THREE.PlaneGeometry(8,8),mat);plane.position.z=2;scene.add(plane);scene.background=new THREE.Color('#000000');
 const sensor=new RGBDSensor(renderer,scene),c=nominalCalibration(96,64);c.depth={...c.depth,fx:79.2,fy:81.5,ppx:41.25,ppy:29.75};c.color={...c.depth};sensor.configure(c);const world=new THREE.Matrix4();
 try{
  test('Pixel centres and asymmetric intrinsics',()=>{const k=c.depth,cam=calibratedCamera(k,world);for(const [u,v] of [[0,0],[95,63],[27,19],[41,30]]){const p=deproject(u,v,2,k),q=p.clone().project(cam),pu=(q.x+1)*k.width/2-.5,pv=(1-q.y)*k.height/2-.5;check(Math.abs(pu-u)<1e-9&&Math.abs(pv-v)<1e-9,'Half-pixel / axis mismatch');}return '4 centre/corner pixels agree with GL raster coordinates';});
  test('GPU depth is optical Z, not ray length',()=>{const f=sensor.capture(world);check(f.valid===96*64,'Missing plane points');let max=0;for(const z of f.depth)max=Math.max(max,Math.abs(z-2));check(max<2e-6,'Plane Z is incorrect');maxError=Math.max(maxError,max);return {pixels:f.valid,maxErrorM:max};});
  test('Tilted plane vs independent ray-plane intersection',()=>{plane.rotation.y=.31;plane.rotation.x=-.12;plane.updateMatrixWorld(true);const n=new THREE.Vector3(0,0,1).applyQuaternion(plane.quaternion),point=plane.position,f=sensor.capture(world);let max=0,worst;for(let v=4;v<60;v++)for(let u=4;u<92;u++){const ray=new THREE.Vector3((u-c.depth.ppx)/c.depth.fx,(v-c.depth.ppy)/c.depth.fy,1),z=n.dot(point)/n.dot(ray);const error=Math.abs(f.depth[v*96+u]-z);if(error>max){max=error;worst={u,v,actual:f.depth[v*96+u],expected:z};}}plane.rotation.set(0,0,0);check(max<5e-5,'Slanted depth incorrect: '+JSON.stringify(worst));maxError=Math.max(maxError,max);return {maxErrorM:max};});
  test('Foreground occludes background',()=>{const box=new THREE.Mesh(new THREE.BoxGeometry(.4,.4,.2),mat);box.position.z=1;scene.add(box);const f=sensor.capture(world);const i=30*96+41;check(Math.abs(f.depth[i]-.9)<2e-6,'Foreground not detected');check(Math.abs(f.depth[5*96+5]-2)<2e-6,'Background missing');scene.remove(box);box.geometry.dispose();return {foreground:f.depth[i],background:f.depth[485]};});
  test('RGB extrinsic projection and color occlusion',()=>{const green=new THREE.Mesh(new THREE.PlaneGeometry(.28,.7),new THREE.MeshBasicMaterial({color:'#00ff00',side:THREE.DoubleSide}));green.position.set(-.14,0,1);scene.add(green);sensor.configure({...c,depth_to_color:{...c.depth_to_color,translation:[.08,0,0]}});const f=sensor.capture(world);let seenGreen=0,seenRed=0,occluded=0;for(let i=0;i<f.valid;i++){const x=f.xyz[i*3],y=f.xyz[i*3+1],z=f.xyz[i*3+2],cx=-.08+(x+.08)/z,cy=y/z;if(z>1.99&&cx>-.26&&cx<-.018&&Math.abs(cy)<.30){check(!f.colorValid[i],'RGB occluder painted a background point');occluded++;}if(!f.colorValid[i])continue;const d=f.colors.subarray(i*3,i*3+3);if(d[1]>200&&d[0]<20)seenGreen++;if(d[0]>120&&d[1]<150)seenRed++;}check(seenGreen>20&&seenRed>200&&occluded>0,'RGB colors/occlusion not captured');sensor.configure(c);scene.remove(green);green.geometry.dispose();green.material.dispose();return {greenPoints:seenGreen,redPoints:seenRed,occluded};});
  test('Near objects invalidate pixels without seeing through them',()=>{const near=new THREE.Mesh(new THREE.BoxGeometry(.05,.05,.05),mat);near.position.z=.12;scene.add(near);const f=sensor.capture(world);check(f.depth[30*96+41]===0,'Below min range leaks background');scene.remove(near);near.geometry.dispose();return 'Min-Z occlusion retained';});
  test('World transform and optical XYZ round trip',()=>{const w=new THREE.Matrix4().compose(new THREE.Vector3(.3,-.2,.6),new THREE.Quaternion().setFromEuler(new THREE.Euler(.2,-.4,.7)),new THREE.Vector3(1,1,1));for(const [u,v] of [[7,5],[43,31],[89,57]]){const p=deproject(u,v,1.4,c.depth),q=p.clone().applyMatrix4(w).applyMatrix4(w.clone().invert()),uv=project(q,c.depth);check(p.distanceTo(q)<1e-12&&Math.abs(uv.u-u)<1e-10&&Math.abs(uv.v-v)<1e-10,'Transform mismatch');}return '3 transformed points return to exact source pixels';});
  test('Z16 quantization and stereo overlap',()=>{plane.position.z=1.23456;const f=sensor.capture(world,{mode:'stereo'});check(f.valid>4000&&f.stereoRejected>0,'Stereo baseline overlap not applied');let max=0;for(const z of f.depth)if(z)max=Math.max(max,Math.abs(z-1.23456));check(max<=.000501,'Quantization exceeds 0.5 mm');plane.position.z=2;return {maxErrorMm:max*1000,rejected:f.stereoRejected};});
  test('Full 1280 x 720 plane, no decimation',()=>{const big=nominalCalibration(1280,720);big.color={...c.color};sensor.configure(big);const f=sensor.capture(world);check(f.valid===1280*720&&f.xyz.length===f.valid*3,'Full resolution points missing');sensor.configure(c);return {points:f.valid,ms:f.ms};});
  test('Calibration validation rejects distortion and bad rotations',()=>{let rejected=0;for(const bad of [{...c,depth:{...c.depth,model:'brown_conrady'}},{...c,depth_to_color:{rotation:[2,0,0,0,1,0,0,0,1],translation:[0,0,0]}},{...c,depth_scale:0}])try{validateCalibration(bad);}catch{rejected++;}check(rejected===3,'Invalid calibration accepted');return '3 invalid calibrations rejected';});
  test('PLY retains every point and pixel index',()=>{const f=sensor.capture(world),buffer=binaryPLY(f,true),bytes=new Uint8Array(buffer),text=new TextDecoder().decode(bytes.subarray(0,700)),length=text.indexOf('end_header\n')+11;check(length>11&&buffer.byteLength===length+f.valid*20,'PLY layout mismatch');const view=new DataView(buffer);for(const i of [0,f.valid-1])check(view.getUint32(length+i*20+16,true)===f.pixels[i],'PLY pixel order mismatch');return {bytes:buffer.byteLength,points:f.valid};});
 }finally{sensor.dispose();plane.geometry.dispose();mat.dispose();}
 return {timestamp:new Date().toISOString(),passed:results.every(x=>x.passed),maxErrorMm:maxError*1000,tests:results};
}
