/**:
  ros__parameters:
    # Verified calibration for Realsense setup(rol,pith.yawは degree)
    x: 0.434
    y: -0.693
    z: 0.279
    roll: -103.8
    pitch: -28.9
    yaw: -3.4
    
    target_frame: "base_link"
    input_topic: "/camera/camera/depth/color/points"
    output_topic: "/camera/transformed_points"
