cmake_minimum_required(VERSION 3.8)
project(arrow_visualization)
find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(std_msgs REQUIRED)
install(DIRECTORY include/ DESTINATION include)
ament_export_include_directories(include)
ament_export_dependencies(geometry_msgs visualization_msgs std_msgs)
ament_package()
